app:
  port: 3003
  site:
    brand: Proof of Existence on Bitcoin Clashic
    logo: "/theme/logo.svg"
    title: Proof of Existence TNET/BCHC
    slogan: Written forever.
    tagline: Instant & Secure Proof of Existence for Any Document.
    email: bitcoin@clashic.cash
    keywords:
      - blockchain
      - notary
      - proof of existence
      - bitcoin
      - p2p
      - anonymous
      - secure
      - permanent
      - distributed
      - documents
      - agreements
      - contracts
  url:
    scheme: http
    host: localhost
    port: 3003
  magicNumber: 0x12b2dcf0
  defaultChain: bchc
  defaultNetwork: mainnet

social:
  twitter: BitcoinClashic
  telegram: TitleNetwork
  github: Bitcoin-Clashic

services:
  insight:
    bchc:
      mainnet:
        url: https://insight.clashic.cash
        api: /api

db:
  path: /var/lib/poe_db/poex-database

chains:
  bchc:
    networks:
      mainnet:
        incomingPrivateKey: 
        outgoingPublicKey: 
        documentPrice: 200000
        feeMultiplier: 4

mail:
  from: proofx@localhost
  to: proofx@localhost

nodemailer:
  options:
